apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "teamcity.fullname" . }}-agent
  labels:
    app: {{ template "teamcity.name" . }}-agent
    chart: {{ template "teamcity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.agent.replicaCount }}
  serviceName: {{ template "teamcity.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "teamcity.name" . }}-agent
      release: {{ .Release.Name }}
  volumeClaimTemplates:
    - metadata:
        name: agent-data
        {{- if .Values.agent.dataStorage.annotations }}
        {{- include ".Values.agent.dataStorage.annotations" . | nindent 6 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.agent.dataStorage.accessMode | default "ReadWriteOnce" }}
        resources:
          requests:
            storage: {{ .Values.agent.dataStorage.size }}
          {{- if .Values.agent.dataStorage.storageClassName }}
        storageClassName: {{ .Values.agent.dataStorage.storageClassName }}
          {{- end }}
    - metadata:
        name: dind-certs-ca
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: "10Mi"
        storageClassName: {{ .Values.agent.dindStorageClass }}
    - metadata:
        name: dind-certs-client
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: "10Mi"
        storageClassName: {{ .Values.agent.dindStorageClass }}
  template:
    metadata:
      labels:
        app: {{ template "teamcity.name" . }}-agent
        release: {{ .Release.Name }}
      {{- if .Values.agent.podAnnotations }}
      annotations:
{{ toYaml .Values.agent.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      volumes:
        - name: agent-tmp
          emptyDir: {}
        - name: agent-work
          emptyDir: {}
      containers:
        - name: {{ .Chart.Name }}-agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_URL
              value: "http://{{ template "teamcity.fullname" . }}:8111"
            - name: DOCKER_HOST
              value: "tcp://localhost:2376"
            - name: DOCKER_TLS_VERIFY
              value: "1"
          volumeMounts:
            - name:  agent-data
              mountPath: /data/teamcity_agent/conf
            - name:  dind-certs-client
              mountPath: /root/.docker
            - name: agent-tmp
              mountPath: /opt/buildagent/temp
            - name: agent-work
              mountPath: /opt/buildagent/work
          resources:
{{ toYaml .Values.agent.resources | indent 12 }}
        - name: {{ .Chart.Name }}-agent-dind-sidecar
          image: docker:dind
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          env:
            - name: DOCKER_TLS_CERTDIR
              value: "/certs"
          volumeMounts:
            - name:  dind-certs-ca
              mountPath: /certs/ca
            - name:  dind-certs-client
              mountPath: /certs/client
            - name: agent-tmp
              mountPath: /opt/buildagent/temp
            - name: agent-work
              mountPath: /opt/buildagent/work
      {{- if .Values.agent.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.agent.imagePullSecrets | indent 8 }}
      {{- end }}
    {{- with .Values.agent.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.agent.priorityClassName }}
      priorityClassName: "{{ .Values.agent.priorityClassName }}"
    {{- end }}
