apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "teamcity.fullname" . }}-agent
  labels:
    app: {{ template "teamcity.name" . }}-agent
    chart: {{ template "teamcity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.agent.replicaCount }}
  serviceName: {{ template "teamcity.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "teamcity.name" . }}-agent
      release: {{ .Release.Name }}
  volumeClaimTemplates:
    - metadata:
        name: agent-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: "10Gi"
        storageClassName: "gp2"
  template:
    metadata:
      labels:
        app: {{ template "teamcity.name" . }}-agent
        release: {{ .Release.Name }}
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: {{ .Chart.Name }}-agent
          image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SERVER_URL
              value: "http://{{ template "teamcity.fullname" . }}:8111"
          volumeMounts:
            - name:  agent-data
              mountPath: /data/teamcity_agent/conf
          resources:
{{ toYaml .Values.agent.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
