apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "teamcity.fullname" . }}
  labels:
    app: {{ template "teamcity.name" . }}
    chart: {{ template "teamcity.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ template "teamcity.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "teamcity.name" . }}
      release: {{ .Release.Name }}
  volumeClaimTemplates:
    - metadata:
        name: server-data
        {{- if .Values.dataStorage.annotations }}
        {{- include ".Values.dataStorage.annotations" . | nindent 6 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.dataStorage.accessMode | default "ReadWriteOnce" }}
        resources:
          requests:
            storage: {{ .Values.dataStorage.size }}
          {{- if .Values.dataStorage.storageClassName }}
        storageClassName: {{ .Values.dataStorage.storageClassName }}
          {{- end }}
  template:
    metadata:
      labels:
        app: {{ template "teamcity.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name:  server-data
              mountPath: /data/teamcity_server/datadir
          ports:
            - name: http
              containerPort: 8111
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- if .Values.priorityClassName }}
      priorityClassName: "{{ .Values.priorityClassName }}"
    {{- end }}
